name: flutter_application_kasir2
description: "Aplikasi Smart-Cart & E-Catalog"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.1
  provider: ^6.1.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true